import { useState, useMemo } from 'react';
import { useConnection, useWallet } from '@solana/wallet-adapter-react';
import { PublicKey, SystemProgram, LAMPORTS_PER_SOL, SYSVAR_INSTRUCTIONS_PUBKEY, Ed25519Program, Transaction } from '@solana/web3.js';
import * as anchor from '@coral-xyz/anchor';
import { IDL, NeonContracts } from '../idl/neon_contracts';

// The Program ID generated by `anchor init` deployed to devnet
const PROGRAM_ID = new PublicKey(import.meta.env.VITE_PROGRAM_ID || "ARcy8Hgks4bfNoYrrdCunrHbvE1dR8kiFHBCRu1Gw6Gi");

import { Buffer } from 'buffer';

// Assign Buffer to window for Anchor if it's missing (Vite polyfill sometimes fails)
if (typeof window !== 'undefined' && !window.Buffer) {
    window.Buffer = Buffer;
}

export function useRankedMatch() {
    const { connection } = useConnection();
    const wallet = useWallet();
    const [loading, setLoading] = useState(false);

    // Initialize Anchor Program
    const program = useMemo(() => {
        try {
            if (!wallet || !wallet.publicKey || !wallet.signTransaction) return null;

            const anchorWallet = {
                publicKey: wallet.publicKey,
                signTransaction: wallet.signTransaction,
                signAllTransactions: wallet.signAllTransactions || (async (txs: any[]) => txs),
            };

            const provider = new anchor.AnchorProvider(connection as anchor.web3.Connection, anchorWallet, {
                preflightCommitment: 'confirmed',
            });

            return new anchor.Program<NeonContracts>(IDL, PROGRAM_ID, provider);
        } catch (err) {
            console.error("Failed to initialize Anchor program:", err);
            return null;
        }
    }, [connection, wallet]);

    /**
     * Helper to derive PDA addresses for the match and vault.
     * PDA seeds have a 32-byte limit. We strip hyphens from UUIDs to 
     * guarantee the string fits into 32 bytes.
     */
    const getMatchPDAs = (matchId: string, playerPubKey?: PublicKey) => {
        // Strip hyphens and ensure it's max 32 chars for the seed
        const seedStr = matchId.replace(/-/g, '').substring(0, 32);

        const [matchPubkey] = PublicKey.findProgramAddressSync(
            [Buffer.from("match"), Buffer.from(seedStr)],
            PROGRAM_ID
        );

        const [vaultPubkey] = PublicKey.findProgramAddressSync(
            [Buffer.from("vault"), matchPubkey.toBuffer()],
            PROGRAM_ID
        );

        let entryPubkey: PublicKey | null = null;
        if (playerPubKey) {
            [entryPubkey] = PublicKey.findProgramAddressSync(
                [Buffer.from("entry"), matchPubkey.toBuffer(), playerPubKey.toBuffer()],
                PROGRAM_ID
            );
        }

        return { matchPubkey, vaultPubkey, entryPubkey, seedStr };
    };

    /**
     * Helper to cleanly parse anchor errors
     */
    const parseAnchorError = (err: any) => {
        if (err instanceof anchor.AnchorError) {
            return `AnchorError (${err.error.errorCode.number}): ${err.error.errorMessage}`;
        }
        if (err.message) return err.message;
        return 'An unknown transaction error occurred';
    };

    /**
     * Create a new match escrow.
     */
    const createMatch = async (matchId: string, entryFeeSOL: number, maxPlayers: number = 2) => {
        if (!program || !wallet.publicKey) throw new Error("Wallet not connected");
        setLoading(true);

        try {
            const { matchPubkey, seedStr } = getMatchPDAs(matchId);
            const feeBN = new anchor.BN(entryFeeSOL * LAMPORTS_PER_SOL);

            const tx = await program.methods
                .createMatch(seedStr, feeBN, maxPlayers)
                .accounts({
                    matchAccount: matchPubkey,
                    funder: wallet.publicKey,
                    systemProgram: SystemProgram.programId,
                })
                .rpc();

            console.log("Match created. TX:", tx);
            return { signature: tx, matchPubkey };
        } catch (error) {
            console.error("Failed to create match:", parseAnchorError(error));
            throw error;
        } finally {
            setLoading(false);
        }
    };

    /**
     * Deposit SOL into an existing match's escrow vault.
     */
    const joinMatch = async (matchId: string) => {
        if (!program || !wallet.publicKey) throw new Error("Wallet not connected");
        setLoading(true);

        try {
            const { matchPubkey, vaultPubkey, entryPubkey } = getMatchPDAs(matchId, wallet.publicKey);

            // 1. Fetch Match Account to verify entry fee
            const matchAccount = await (program.account as any).matchAccount.fetch(matchPubkey);
            const entryFeeLamports = matchAccount.entryFee.toNumber();

            // 2. Pre-Join Balance Check
            const playerBalance = await connection.getBalance(wallet.publicKey);

            // Checking sufficient balance + buffer for rent/network fee (~0.005 SOL)
            const MIN_REQUIRED_BALANCE = entryFeeLamports + 5000000;

            if (playerBalance < MIN_REQUIRED_BALANCE) {
                throw new Error(`Insufficient Neon. You need at least ${MIN_REQUIRED_BALANCE / LAMPORTS_PER_SOL} Neon.`);
            }

            const tx = await program.methods
                .joinMatch()
                .accounts({
                    matchAccount: matchPubkey,
                    playerEntry: entryPubkey!,
                    player: wallet.publicKey,
                    escrowVault: vaultPubkey,
                    systemProgram: SystemProgram.programId,
                })
                .rpc();

            console.log("Joined match. TX:", tx);
            return { signature: tx, entryPubkey };
        } catch (error: any) {
            if (error.message?.includes('already in use') || error.message?.includes('0x0')) {
                console.error("Failed to join match: You have already joined this match.");
                throw new Error("You have already joined this match.");
            } else {
                console.error("Failed to join match:", parseAnchorError(error));
            }
            throw error;
        } finally {
            setLoading(false);
        }
    };

    /**
     * Fetch match state to check player counts and lock status.
     */
    const fetchMatch = async (matchId: string) => {
        if (!program) return null;
        try {
            const { matchPubkey } = getMatchPDAs(matchId);
            return await (program.account as any).matchAccount.fetch(matchPubkey);
        } catch (e) {
            console.log("Match not found or error fetching:", e);
            return null;
        }
    };

    /**
     * Derive the ProgramConfig PDA (seeds = ["config"])
     */
    const getConfigPDA = () => {
        const [configPubkey] = PublicKey.findProgramAddressSync(
            [Buffer.from("config")],
            PROGRAM_ID
        );
        return configPubkey;
    };

    /**
     * Lock a match to prevent new players from joining.
     * Transitions match state from Waiting -> Locked.
     * Any signer can lock it (in the MVP contract).
     */
    const lockMatch = async (matchId: string) => {
        if (!program || !wallet.publicKey) throw new Error("Wallet not connected");
        setLoading(true);

        try {
            const { matchPubkey } = getMatchPDAs(matchId);

            const tx = await program.methods
                .lockMatch()
                .accounts({
                    matchAccount: matchPubkey,
                    signer: wallet.publicKey,
                })
                .rpc();

            console.log("Match locked. TX:", tx);
            return { signature: tx };
        } catch (error) {
            console.error("Failed to lock match:", parseAnchorError(error));
            throw error;
        } finally {
            setLoading(false);
        }
    };

    /**
     * Initialize the program config (ONE-TIME setup).
     * Sets up admin, oracle pubkey, fee basis points, and treasury.
     * Must be called once before distributeRewards can work.
     */
    const initializeProgram = async (feeBasisPoints: number, oraclePubkey: PublicKey) => {
        if (!program || !wallet.publicKey) throw new Error("Wallet not connected");
        setLoading(true);

        try {
            const configPubkey = getConfigPDA();

            const tx = await program.methods
                .initializeProgram(feeBasisPoints, oraclePubkey)
                .accounts({
                    config: configPubkey,
                    admin: wallet.publicKey,
                    systemProgram: SystemProgram.programId,
                })
                .rpc();

            console.log("Program initialized. TX:", tx);
            return { signature: tx, configPubkey };
        } catch (error) {
            console.error("Failed to initialize program:", parseAnchorError(error));
            throw error;
        } finally {
            setLoading(false);
        }
    };

    /**
     * Fetch the ProgramConfig account to check if initialized.
     */
    const fetchConfig = async () => {
        if (!program) return null;
        try {
            const configPubkey = getConfigPDA();
            return await (program.account as any).programConfig.fetch(configPubkey);
        } catch (e) {
            console.log("Config not found (not initialized yet):", e);
            return null;
        }
    };

    /**
     * Distribute rewards based on an Oracle signature.
     * The oracle signature array and winner public key must perfectly match the
     * matchId data that was signed.
     */
    const distributeRewards = async (matchId: string, winnerPubkey: PublicKey, signature: number[]) => {
        if (!program || !wallet.publicKey) throw new Error("Wallet not connected");
        setLoading(true);

        try {
            const configPubkey = getConfigPDA();
            const config: any = await fetchConfig();
            
            if (!config) {
                throw new Error("Program config not found. Have you initialized the program?");
            }

            const { matchPubkey, vaultPubkey, seedStr } = getMatchPDAs(matchId);

            // 1. Build message identically to the Oracle
            const messageBytes = Buffer.concat([
                Buffer.from(seedStr, 'utf8'),
                winnerPubkey.toBuffer()
            ]);

            // 2. Wrap the Ed25519 Native Program signature verification
            const ed25519Ix = Ed25519Program.createInstructionWithPublicKey({
                publicKey: config.oracle.toBytes(),
                message: messageBytes,
                signature: Buffer.from(signature),
            });

            // 3. Prepare our specific Anchor instruction
            const distributeIx = await program.methods
                .distributeRewards(seedStr, winnerPubkey, signature)
                .accounts({
                    config: configPubkey,
                    matchAccount: matchPubkey,
                    winner: winnerPubkey,
                    treasury: config.treasury,
                    escrowVault: vaultPubkey,
                    instructionSysvar: SYSVAR_INSTRUCTIONS_PUBKEY,
                    systemProgram: SystemProgram.programId,
                })
                .instruction();

            // 4. Combine them into a single dual-instruction transaction
            const tx = new Transaction().add(ed25519Ix, distributeIx);
            
            // Anchor 0.26+ `sendAndConfirm` handles the wallet transaction signing
            const txSignature = await program.provider.sendAndConfirm!(tx, [], { commitment: 'confirmed' });
            
            console.log("Rewards Distributed successfully! TX:", txSignature);
            return { signature: txSignature };
        } catch (error) {
            console.error("Failed to distribute rewards:", parseAnchorError(error));
            throw error;
        } finally {
            setLoading(false);
        }
    };

    return {
        createMatch,
        joinMatch,
        lockMatch,
        fetchMatch,
        distributeRewards,
        initializeProgram,
        fetchConfig,
        getMatchPDAs,
        getConfigPDA,
        loading,
        isReady: !!program,
    };
}
